# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\pjjoyce\Dropbox\00_My_Software\futura\futura_ui\app\ui\ui_files\markets_wizard.ui',
# licensing of 'C:\Users\pjjoyce\Dropbox\00_My_Software\futura\futura_ui\app\ui\ui_files\markets_wizard.ui' applies.
#
# Created: Fri Dec 13 12:59:03 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MarketsWizard(object):
    def setupUi(self, MarketsWizard):
        MarketsWizard.setObjectName("MarketsWizard")
        MarketsWizard.resize(1343, 819)
        MarketsWizard.setWizardStyle(QtWidgets.QWizard.ModernStyle)
        self.wizardPage1 = QtWidgets.QWizardPage()
        self.wizardPage1.setObjectName("wizardPage1")
        self.gridLayout = QtWidgets.QGridLayout(self.wizardPage1)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.wizardPage1)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.wizardPage1)
        self.label.setMaximumSize(QtCore.QSize(16777215, 70))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.filterLayout = QtWidgets.QGridLayout()
        self.filterLayout.setObjectName("filterLayout")
        self.verticalLayout_2.addLayout(self.filterLayout)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        MarketsWizard.addPage(self.wizardPage1)
        self.wizardPage2 = QtWidgets.QWizardPage()
        self.wizardPage2.setObjectName("wizardPage2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.wizardPage2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.wizardPage2)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.splitter = QtWidgets.QSplitter(self.wizardPage2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.tableView = QtWidgets.QTableView(self.splitter)
        self.tableView.setMinimumSize(QtCore.QSize(500, 500))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.tableView.setFont(font)
        self.tableView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableView.setAlternatingRowColors(True)
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.tableView.setSortingEnabled(True)
        self.tableView.setObjectName("tableView")
        self.frame = QtWidgets.QFrame(self.splitter)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.graphLayout = QtWidgets.QGridLayout()
        self.graphLayout.setObjectName("graphLayout")
        self.gridLayout_3.addLayout(self.graphLayout, 0, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.splitter)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.frame_2 = QtWidgets.QFrame(self.wizardPage2)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addButton = QtWidgets.QPushButton(self.frame_2)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout.addWidget(self.addButton)
        self.transferButton = QtWidgets.QPushButton(self.frame_2)
        self.transferButton.setEnabled(False)
        self.transferButton.setObjectName("transferButton")
        self.horizontalLayout.addWidget(self.transferButton)
        self.setButton = QtWidgets.QPushButton(self.frame_2)
        self.setButton.setEnabled(False)
        self.setButton.setCheckable(False)
        self.setButton.setChecked(False)
        self.setButton.setObjectName("setButton")
        self.horizontalLayout.addWidget(self.setButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.frame_2)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        MarketsWizard.addPage(self.wizardPage2)
        self.wizardPage = QtWidgets.QWizardPage()
        self.wizardPage.setObjectName("wizardPage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.wizardPage)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.wizardPage)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.wizardPage)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 70))
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_7 = QtWidgets.QLabel(self.wizardPage)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.wizardPage)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.marketLabel = QtWidgets.QLabel(self.wizardPage)
        self.marketLabel.setObjectName("marketLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.marketLabel)
        self.actionLabel = QtWidgets.QLabel(self.wizardPage)
        self.actionLabel.setObjectName("actionLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.actionLabel)
        self.verticalLayout_4.addLayout(self.formLayout)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        MarketsWizard.addPage(self.wizardPage)

        self.retranslateUi(MarketsWizard)
        QtCore.QMetaObject.connectSlotsByName(MarketsWizard)

    def retranslateUi(self, MarketsWizard):
        MarketsWizard.setWindowTitle(QtWidgets.QApplication.translate("MarketsWizard", "Market Wizard", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MarketsWizard", "Choose a market to edit", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MarketsWizard", "On this page you will set up a filter to choose a market to edit.\n"
"\n"
"On the next page you will be able to edit the market.", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MarketsWizard", "Edit Market", None, -1))
        self.addButton.setText(QtWidgets.QApplication.translate("MarketsWizard", "Add alternative providers", None, -1))
        self.transferButton.setText(QtWidgets.QApplication.translate("MarketsWizard", "Transfer production", None, -1))
        self.setButton.setText(QtWidgets.QApplication.translate("MarketsWizard", "Edit production", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MarketsWizard", "Review your choices", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MarketsWizard", "On this page you will check that you\'re happy with the updates to the market about to be carried out.", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MarketsWizard", "Market:", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MarketsWizard", "Actions to be taken:", None, -1))
        self.marketLabel.setText(QtWidgets.QApplication.translate("MarketsWizard", "Not specified", None, -1))
        self.actionLabel.setText(QtWidgets.QApplication.translate("MarketsWizard", "Not specified", None, -1))

