# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\pjjoyce\Dropbox\00_My_Software\futura\futura_ui\app\ui\ui_files\regionalisation_wizard.ui',
# licensing of 'C:\Users\pjjoyce\Dropbox\00_My_Software\futura\futura_ui\app\ui\ui_files\regionalisation_wizard.ui' applies.
#
# Created: Fri Dec 13 12:59:03 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_RegionalisationWizard(object):
    def setupUi(self, RegionalisationWizard):
        RegionalisationWizard.setObjectName("RegionalisationWizard")
        RegionalisationWizard.resize(899, 690)
        RegionalisationWizard.setWizardStyle(QtWidgets.QWizard.ModernStyle)
        RegionalisationWizard.setOptions(QtWidgets.QWizard.HelpButtonOnRight)
        self.wizardPage1 = QtWidgets.QWizardPage()
        self.wizardPage1.setObjectName("wizardPage1")
        self.gridLayout = QtWidgets.QGridLayout(self.wizardPage1)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.wizardPage1)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.wizardPage1)
        self.label.setMaximumSize(QtCore.QSize(16777215, 70))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.filterLayout = QtWidgets.QGridLayout()
        self.filterLayout.setObjectName("filterLayout")
        self.verticalLayout_2.addLayout(self.filterLayout)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        RegionalisationWizard.addPage(self.wizardPage1)
        self.wizardPage2 = QtWidgets.QWizardPage()
        self.wizardPage2.setObjectName("wizardPage2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.wizardPage2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(11, 11, 713, 441))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 70))
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.locationLayout = QtWidgets.QGridLayout()
        self.locationLayout.setObjectName("locationLayout")
        self.verticalLayout_3.addLayout(self.locationLayout)
        RegionalisationWizard.addPage(self.wizardPage2)
        self.wizardPage = QtWidgets.QWizardPage()
        self.wizardPage.setObjectName("wizardPage")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.wizardPage)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(11, 11, 711, 431))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 70))
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.processDescriptionLabel = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.processDescriptionLabel.setFont(font)
        self.processDescriptionLabel.setObjectName("processDescriptionLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.processDescriptionLabel)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.processLabel = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.processLabel.setObjectName("processLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.processLabel)
        self.locationLabel = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.locationLabel.setObjectName("locationLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.locationLabel)
        self.verticalLayout_4.addLayout(self.formLayout)
        RegionalisationWizard.addPage(self.wizardPage)

        self.retranslateUi(RegionalisationWizard)
        QtCore.QMetaObject.connectSlotsByName(RegionalisationWizard)

    def retranslateUi(self, RegionalisationWizard):
        RegionalisationWizard.setWindowTitle(QtWidgets.QApplication.translate("RegionalisationWizard", "Regionalisation Wizard", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("RegionalisationWizard", "Choose a process to regionalise", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("RegionalisationWizard", "On this page you will set up a filter to choose one process which will act as a template for a set of new regionalised versions. On the next page you will choose the new locations where you would like to make this process available.", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("RegionalisationWizard", "Choose the new location(s) for this process", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("RegionalisationWizard", "On this page you will choose the new locations where you would like to make this process available. \n"
"\n"
"Locations where that process already exists have automatically been disabled.", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("RegionalisationWizard", "Review your choices", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("RegionalisationWizard", "On this page you will check that you\'re happy with the regionalisation about to be carried out.", None, -1))
        self.processDescriptionLabel.setText(QtWidgets.QApplication.translate("RegionalisationWizard", "Base process:", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("RegionalisationWizard", "New locations:", None, -1))
        self.processLabel.setText(QtWidgets.QApplication.translate("RegionalisationWizard", "Not specified", None, -1))
        self.locationLabel.setText(QtWidgets.QApplication.translate("RegionalisationWizard", "Not specified", None, -1))

